{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "storymap",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "kgd5jmkf6fcthhhulwwmsyplzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storymap-3.0.1.jar",
          "url": "storymap-3.0.1.jar",
          "size": 14461,
          "sha512": "e732fae176dae2b95fa330a20fa4d233dc13c73187c380ae89da3a9beec6dbab41f2864b27d7ba7da3c26c38245de901a1c82ef808dd812300e83cc53514b6d9",
          "sha256": "9c04a913cacf7809a95e515c561241ae72c9838b7cbe7fa83e21905044279fed",
          "sha1": "ff35f7c81ef00b8bb9f9453679fa3f812674fc01",
          "md5": "267feaf2670fc27170d8a17952dddcc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "sh.pancake",
          "module": "pancake-sauce",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "storymap-3.0.1.jar",
          "url": "storymap-3.0.1.jar",
          "size": 14461,
          "sha512": "e732fae176dae2b95fa330a20fa4d233dc13c73187c380ae89da3a9beec6dbab41f2864b27d7ba7da3c26c38245de901a1c82ef808dd812300e83cc53514b6d9",
          "sha256": "9c04a913cacf7809a95e515c561241ae72c9838b7cbe7fa83e21905044279fed",
          "sha1": "ff35f7c81ef00b8bb9f9453679fa3f812674fc01",
          "md5": "267feaf2670fc27170d8a17952dddcc3"
        }
      ]
    }
  ]
}
