{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "story-network-launch-util",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ihr24r22xncddjnoxch6yceeji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "story-network-launch-util-0.1.0.jar",
          "url": "story-network-launch-util-0.1.0.jar",
          "size": 16092,
          "sha512": "72dc4436df191b6bab03653ae1ee63e71ca06b65b82eb5c6e7704a31dde8dddcc95e065cbd59f878b48567a4b44c5f78739463a6616a0428bf9ae34028bf4fc1",
          "sha256": "433d8982c2d0cbd504c975ca0720afd9e5f81cf595c9314426e8e7498ad50f68",
          "sha1": "955cbe158a79c6a303f633fa6de82c9c0f6945f2",
          "md5": "b4f2bd9af060e812c5056fd92b1cf318"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "story-network-launch-util-0.1.0.jar",
          "url": "story-network-launch-util-0.1.0.jar",
          "size": 16092,
          "sha512": "72dc4436df191b6bab03653ae1ee63e71ca06b65b82eb5c6e7704a31dde8dddcc95e065cbd59f878b48567a4b44c5f78739463a6616a0428bf9ae34028bf4fc1",
          "sha256": "433d8982c2d0cbd504c975ca0720afd9e5f81cf595c9314426e8e7498ad50f68",
          "sha1": "955cbe158a79c6a303f633fa6de82c9c0f6945f2",
          "md5": "b4f2bd9af060e812c5056fd92b1cf318"
        }
      ]
    }
  ]
}
