{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-sauce",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "tyvigmivabcbbpqdjq3vfcoqyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pancake-sauce-0.2.0.jar",
          "url": "pancake-sauce-0.2.0.jar",
          "size": 27803,
          "sha512": "c41b6a228dc629d7e2a16fc6ee60b116f5efa4791b2ebf8950b16557255c2d994b84c1490b26b6b1d9b8b79a416675314139cf21bd4baadc03190e215b433ebd",
          "sha256": "8e6f82d223e6537359dd657fd9e9a732782eeb03504dd9446bfd9a03eb28d34e",
          "sha1": "b0124ff80e171d8d5cab7ff897ee1f2269b5c157",
          "md5": "af6c1d1e49b63360a86783372465ddc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-sauce-0.2.0.jar",
          "url": "pancake-sauce-0.2.0.jar",
          "size": 27803,
          "sha512": "c41b6a228dc629d7e2a16fc6ee60b116f5efa4791b2ebf8950b16557255c2d994b84c1490b26b6b1d9b8b79a416675314139cf21bd4baadc03190e215b433ebd",
          "sha256": "8e6f82d223e6537359dd657fd9e9a732782eeb03504dd9446bfd9a03eb28d34e",
          "sha1": "b0124ff80e171d8d5cab7ff897ee1f2269b5c157",
          "md5": "af6c1d1e49b63360a86783372465ddc7"
        }
      ]
    }
  ]
}
