{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-sauce",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "gzbe5rigmfcypcqg6n2tdgsvj4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pancake-sauce-0.2.0.jar",
          "url": "pancake-sauce-0.2.0.jar",
          "size": 27804,
          "sha512": "c5498df7efe656a9722c226d8512fd416bc0206f817d2c55c6ff7662d0585549b8f5a0f556557b3f4c9c093b47aa62b8e9d81224978af34e6db5d5b1f712d4f8",
          "sha256": "d0cb2386bdaa3f2a1a47b5416d99586c24038f7c8a6e7f2fdcff86cd20c0f633",
          "sha1": "bb4cf3c5292fe8faeff43ac2d119ff2f977ab4f0",
          "md5": "8e4b5bdb579e44728edb69f166706405"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-sauce-0.2.0.jar",
          "url": "pancake-sauce-0.2.0.jar",
          "size": 27804,
          "sha512": "c5498df7efe656a9722c226d8512fd416bc0206f817d2c55c6ff7662d0585549b8f5a0f556557b3f4c9c093b47aa62b8e9d81224978af34e6db5d5b1f712d4f8",
          "sha256": "d0cb2386bdaa3f2a1a47b5416d99586c24038f7c8a6e7f2fdcff86cd20c0f633",
          "sha1": "bb4cf3c5292fe8faeff43ac2d119ff2f977ab4f0",
          "md5": "8e4b5bdb579e44728edb69f166706405"
        }
      ]
    }
  ]
}
