{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "story-network-common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "brhrsdvykzfljpbdyvwsk3ky3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 9,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "story-network-common-1.0.0.jar",
          "url": "story-network-common-1.0.0.jar",
          "size": 22128,
          "sha512": "7ffb7856e694cf82f5d6e4320b690cfabc10e0746a6b404333f513aee8e5cff505c45c790332856e07d892824f6e87c191bface685b89552335dd8db051c699e",
          "sha256": "b8798d9a4a0822a7fb71b04cf0de91561c39ceecb21313e13c17991fdc89d983",
          "sha1": "74eda47a48a9fc611735f7b7d017165415e4e07f",
          "md5": "923c143529c319a196ced86b98f6b70b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 9,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "story-network-common-1.0.0.jar",
          "url": "story-network-common-1.0.0.jar",
          "size": 22128,
          "sha512": "7ffb7856e694cf82f5d6e4320b690cfabc10e0746a6b404333f513aee8e5cff505c45c790332856e07d892824f6e87c191bface685b89552335dd8db051c699e",
          "sha256": "b8798d9a4a0822a7fb71b04cf0de91561c39ceecb21313e13c17991fdc89d983",
          "sha1": "74eda47a48a9fc611735f7b7d017165415e4e07f",
          "md5": "923c143529c319a196ced86b98f6b70b"
        }
      ]
    }
  ]
}
