{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-sauce",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "flqhwed3onesnjxgcjbnhdlnni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pancake-sauce-0.1.0.jar",
          "url": "pancake-sauce-0.1.0.jar",
          "size": 26744,
          "sha512": "4d5cb57872cbc3d440cce275165b91509494354bf8c068cc59c91d7cdb5d0a880fb5098ddac310c4c7116c8edd5af389070bef583609b0c278a078c148fbb4a5",
          "sha256": "188cf905952b184259cf1afb444a101b16a40f9a891ffe1eb25692a994cb8009",
          "sha1": "f339d636f9c51648a2bc01de0b27b106ae68e7aa",
          "md5": "06fe054cb0ff45f77d5f55488488af22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-sauce-0.1.0.jar",
          "url": "pancake-sauce-0.1.0.jar",
          "size": 26744,
          "sha512": "4d5cb57872cbc3d440cce275165b91509494354bf8c068cc59c91d7cdb5d0a880fb5098ddac310c4c7116c8edd5af389070bef583609b0c278a078c148fbb4a5",
          "sha256": "188cf905952b184259cf1afb444a101b16a40f9a891ffe1eb25692a994cb8009",
          "sha1": "f339d636f9c51648a2bc01de0b27b106ae68e7aa",
          "md5": "06fe054cb0ff45f77d5f55488488af22"
        }
      ]
    }
  ]
}
