{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-server",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ij2tte3h7nazpmw6c3q27xaevu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 9,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pancake-server-1.0.0.jar",
          "url": "pancake-server-1.0.0.jar",
          "size": 66214,
          "sha512": "8aa4e49dc9440ecd8a34389fb6e1e789c437ef1da8927d2c5294d75140129bc6183e5eb5fe46d859ac774f228f673bfed2a728030274f2e2b4418e80fbf431ee",
          "sha256": "32c31cf87628affae97ccebd2750bac69a88d5d738147a86826491619750fe00",
          "sha1": "7751f47602c7d65dba59b63d9e5bc183c0db1a8c",
          "md5": "0a50e6951143eff49fee924f8f56178c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 9,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "sh.pancake",
          "module": "story-network-common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.heartpattern",
          "module": "mcremapper",
          "version": {
            "requires": "2.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-server-1.0.0.jar",
          "url": "pancake-server-1.0.0.jar",
          "size": 66214,
          "sha512": "8aa4e49dc9440ecd8a34389fb6e1e789c437ef1da8927d2c5294d75140129bc6183e5eb5fe46d859ac774f228f673bfed2a728030274f2e2b4418e80fbf431ee",
          "sha256": "32c31cf87628affae97ccebd2750bac69a88d5d738147a86826491619750fe00",
          "sha1": "7751f47602c7d65dba59b63d9e5bc183c0db1a8c",
          "md5": "0a50e6951143eff49fee924f8f56178c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-server-1.0.0-all.jar",
          "url": "pancake-server-1.0.0-all.jar",
          "size": 18562715,
          "sha512": "19bf2b7eb0cf79f2f7cf214b9b071873d785163c743e361ae8220d5e4d597b30239d44fe31f80d7f8b7daa33d0d086a3f81e12f78bc2b39a24d89b7b900aeb6b",
          "sha256": "948a963cc52f53413360eb5b83cc1d2676656b52c5a95ee06ac87151d007aa31",
          "sha1": "4b17a2372f025a551fcc3bbbf5694b917a7877d8",
          "md5": "02c14e72cba61e554a32e0eeeca450fb"
        }
      ]
    }
  ]
}
