{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-server",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xl56tzt3gfe7hbwgkz3gs4y6g4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 9,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pancake-server-1.0.0.jar",
          "url": "pancake-server-1.0.0.jar",
          "size": 63124,
          "sha512": "4fcdbf11b60435df7c9d02abdfbfb0bace9a0b4a482b1d303260699c66641ad7acd233ce7b4a5675e45110ea67ac0ded193bbaf03a20a916bf2524a53545435b",
          "sha256": "f5d4bcb0e1d891303ad4e8c9944a384427b3edb631240173d890bdcebaeb59d6",
          "sha1": "9f3376d7d15e1107c4b152ed0ffaf03af4803b24",
          "md5": "43eff48fcae7e271f6ae6af56853b24e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 9,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "sh.pancake",
          "module": "story-network-common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.heartpattern",
          "module": "mcremapper",
          "version": {
            "requires": "2.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-server-1.0.0.jar",
          "url": "pancake-server-1.0.0.jar",
          "size": 63124,
          "sha512": "4fcdbf11b60435df7c9d02abdfbfb0bace9a0b4a482b1d303260699c66641ad7acd233ce7b4a5675e45110ea67ac0ded193bbaf03a20a916bf2524a53545435b",
          "sha256": "f5d4bcb0e1d891303ad4e8c9944a384427b3edb631240173d890bdcebaeb59d6",
          "sha1": "9f3376d7d15e1107c4b152ed0ffaf03af4803b24",
          "md5": "43eff48fcae7e271f6ae6af56853b24e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-server-1.0.0-all.jar",
          "url": "pancake-server-1.0.0-all.jar",
          "size": 18559625,
          "sha512": "5e1be1dc36864058927689fa62eec931c3763c0b1269568635780642c99887e51c48f83c0c7e0accc590b66e2d430616eee0d9f814cff6217a862f19937c3db2",
          "sha256": "35c04da6bfc03445fd524e0da2fd79bee3bf0a06464f18e720e4186c38a8da56",
          "sha1": "3b83f12d87e1a1e026f8599fd501694f04dc421b",
          "md5": "2c403162f40e23d88d6760bfbfcfcfe5"
        }
      ]
    }
  ]
}
