{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-server",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "oomp6dm3v5azrnsgx44izklhdy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 9,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pancake-server-1.0.0.jar",
          "url": "pancake-server-1.0.0.jar",
          "size": 55048,
          "sha512": "316ad198b800fc0efe28e38191333d496abe090d5aa393ee30ee5c2d946795bcc93e20b7bfadc7204ad81400c00545a9d66c5fa157c04a7a38a7b0e6bb636898",
          "sha256": "06e59f7efec29d19ff6950f86fd33136cb38c43a0ae6840314bbb989510738cb",
          "sha1": "e90fedbb1ad049ff543f7ffb4b74ff4e0e32afac",
          "md5": "9e443e060cea32e98cde2ee60ad8b057"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 9,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "sh.pancake",
          "module": "story-network-common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.heartpattern",
          "module": "mcremapper",
          "version": {
            "requires": "2.0.2-SNAPSHOT"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-server-1.0.0.jar",
          "url": "pancake-server-1.0.0.jar",
          "size": 55048,
          "sha512": "316ad198b800fc0efe28e38191333d496abe090d5aa393ee30ee5c2d946795bcc93e20b7bfadc7204ad81400c00545a9d66c5fa157c04a7a38a7b0e6bb636898",
          "sha256": "06e59f7efec29d19ff6950f86fd33136cb38c43a0ae6840314bbb989510738cb",
          "sha1": "e90fedbb1ad049ff543f7ffb4b74ff4e0e32afac",
          "md5": "9e443e060cea32e98cde2ee60ad8b057"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-server-1.0.0-all.jar",
          "url": "pancake-server-1.0.0-all.jar",
          "size": 18474504,
          "sha512": "78370e55b61ebc51d68550644a52306ba04b7eab869f2d963e20155966243b227e940b52b716e4b5873e1504e7cf57208cfcf4bf2c37280914c1721a898a77b2",
          "sha256": "d4f095c058dd6a57f61a9a47765e25e80e1d9f28343a6a7afbcb284aaa5dce9f",
          "sha1": "34d51520501aa70404d2be246b6b28744c64ab55",
          "md5": "210a97eefb0dea0cb30e0778f288730b"
        }
      ]
    }
  ]
}
