{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-launcher",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-launcher-0.3.0.jar",
          "url": "pancake-launcher-0.3.0.jar",
          "size": 24520,
          "sha512": "4f05055082d88f9774f18c131fbe708bd4d6e7a9f09c2d79d7326bdbe82e9750a2e4deff518b233eff2dc1a4aa67a8072acccd1188bb3083346160a63158c266",
          "sha256": "c78ab063ba76e2a1336c28ad4d20041c435a7795eb6e175ac23ea228322d7180",
          "sha1": "1e72dcd9c44d7622acc5af2bb65369455236c047",
          "md5": "72e65cb67220c41ac86dafedb885ebad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "pancake-sauce",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.6.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-launcher-0.3.0.jar",
          "url": "pancake-launcher-0.3.0.jar",
          "size": 24520,
          "sha512": "4f05055082d88f9774f18c131fbe708bd4d6e7a9f09c2d79d7326bdbe82e9750a2e4deff518b233eff2dc1a4aa67a8072acccd1188bb3083346160a63158c266",
          "sha256": "c78ab063ba76e2a1336c28ad4d20041c435a7795eb6e175ac23ea228322d7180",
          "sha1": "1e72dcd9c44d7622acc5af2bb65369455236c047",
          "md5": "72e65cb67220c41ac86dafedb885ebad"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-launcher-0.3.0-all.jar",
          "url": "pancake-launcher-0.3.0-all.jar",
          "size": 7395990,
          "sha512": "f4b027871080006000a8065d296b5285e316e925e04aed2fd9c14d6140e905598265bde0d0e93ddd5a3aaf20f017e4da8c0da120afd587f55ae5929e18112b26",
          "sha256": "bfb6750a6c2ae53e67f3f347be1fc4ca760b1d0efa367cd00995cb80b4e278ad",
          "sha1": "f1843248734be4cff6a6f8229957383146f011b5",
          "md5": "281bba57e5be6e151c736dbc1faa67da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-launcher-0.3.0-sources.jar",
          "url": "pancake-launcher-0.3.0-sources.jar",
          "size": 15345,
          "sha512": "a2dc5fd5b8c60028734ffbfbb654f107fc2018e839809e1e3000eea1f798da7fd14e4f0590b1bf0815f0914136fad6d85fd6d32dd3b777f8236697174939bee1",
          "sha256": "145584047c1f52ac0d31f4ac22eb2b6a8d30ffb0cea0197dc1dcb27a713f1bf7",
          "sha1": "a727c8b0d63adb82cbedda50300293172ef01449",
          "md5": "654766826e655cec9b226df2b1517504"
        }
      ]
    }
  ]
}
