{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-launcher",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-launcher-0.3.0.jar",
          "url": "pancake-launcher-0.3.0.jar",
          "size": 24520,
          "sha512": "11281024c778eb13285ef638efa00eaacd3691367b3d8bc523410020ba48f3e2c590106d7a6b1f336edb5b7133d2cde1c6d032062c3dc06a0d58542386403423",
          "sha256": "b3e3201f775d9efdb43041e938c97dd016505d2afc17c9e107df30d7a71a6b00",
          "sha1": "8b9416c8954a3a64c5b15cd5e46ece870386e524",
          "md5": "8226598a778f0d705b2bc7b02c0e6cf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "pancake-sauce",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.6.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-launcher-0.3.0.jar",
          "url": "pancake-launcher-0.3.0.jar",
          "size": 24520,
          "sha512": "11281024c778eb13285ef638efa00eaacd3691367b3d8bc523410020ba48f3e2c590106d7a6b1f336edb5b7133d2cde1c6d032062c3dc06a0d58542386403423",
          "sha256": "b3e3201f775d9efdb43041e938c97dd016505d2afc17c9e107df30d7a71a6b00",
          "sha1": "8b9416c8954a3a64c5b15cd5e46ece870386e524",
          "md5": "8226598a778f0d705b2bc7b02c0e6cf8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-launcher-0.3.0-all.jar",
          "url": "pancake-launcher-0.3.0-all.jar",
          "size": 7398617,
          "sha512": "a465cddd66fa150ec9cc65581401b0e19996aecf19a0db21556153934bf0084287a180ab8b53a1a2011e763bc71de863aa3f8fcb9e2b043f430e6356e6e1d8f8",
          "sha256": "ac4a18420a4a8365af721c0b307fe7aa7c3dd209f2181db7ec3e82fe1087bab7",
          "sha1": "35039f2780c88ed460e5649807e264073285075a",
          "md5": "51293b61c225e3fa9f84ed0e52abc8a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-launcher-0.3.0-sources.jar",
          "url": "pancake-launcher-0.3.0-sources.jar",
          "size": 15345,
          "sha512": "243038dd75f446a1a95e95ded010e7ce4615052b2e656bfc5f0d66be459550b15d9356cad0b61283beecac45aa1e0de518c1852794fa9e5f54772a820ec1106c",
          "sha256": "f3af8060444449b2f882c312f814cd425bd778b3ba2a7748adfa384794706ebd",
          "sha1": "7184509e9969355c223bd52063fbc77949013083",
          "md5": "574c37240e7f9127eb2b780f43e1127a"
        }
      ]
    }
  ]
}
