{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "storymap",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "g5e43oxinbdide6tmb75oo3eae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storymap-2.0.0.jar",
          "url": "storymap-2.0.0.jar",
          "size": 14401,
          "sha512": "8a7716bd129165778e41fd263a88a3785935eed391646a3b1a70e7f8c993cdde99ad05c125a51053ebf9c2520ade5acbaf28c0f31ae24076fea45ad5dc1e51c1",
          "sha256": "274b7790e6a669fa36be6c67a3fb4d586c3d95ae11d146b3dcb44802cbc59f31",
          "sha1": "b34a105c4620fb0b40ba74821e8cabf5ed2a7025",
          "md5": "47784e45012d9815f0b076ec6b9ae9dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "story-network-common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "sh.pancake",
          "module": "pancake-sauce",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "storymap-2.0.0.jar",
          "url": "storymap-2.0.0.jar",
          "size": 14401,
          "sha512": "8a7716bd129165778e41fd263a88a3785935eed391646a3b1a70e7f8c993cdde99ad05c125a51053ebf9c2520ade5acbaf28c0f31ae24076fea45ad5dc1e51c1",
          "sha256": "274b7790e6a669fa36be6c67a3fb4d586c3d95ae11d146b3dcb44802cbc59f31",
          "sha1": "b34a105c4620fb0b40ba74821e8cabf5ed2a7025",
          "md5": "47784e45012d9815f0b076ec6b9ae9dd"
        }
      ]
    }
  ]
}
