{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "storymap",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ahjctkrjsfckfem76ghhzahiwi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storymap-2.0.0.jar",
          "url": "storymap-2.0.0.jar",
          "size": 14407,
          "sha512": "4b7a5b5a02fb873e224634a2201f1e4d10017f0cc56e34816d85974284b4f11c05cbd3712d6a10723f30affed2415d3742942261247e9e8cc66625e7251e675a",
          "sha256": "379ffd3dfe040c8abe4f4d6016f71736105cca16be42c7bf01d5ca15732b17bd",
          "sha1": "712312a11616f05af38e958347dabc04d71e9923",
          "md5": "a973be7407ca836f26b1bac1f848171f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "story-network-common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "sh.pancake",
          "module": "pancake-sauce",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "storymap-2.0.0.jar",
          "url": "storymap-2.0.0.jar",
          "size": 14407,
          "sha512": "4b7a5b5a02fb873e224634a2201f1e4d10017f0cc56e34816d85974284b4f11c05cbd3712d6a10723f30affed2415d3742942261247e9e8cc66625e7251e675a",
          "sha256": "379ffd3dfe040c8abe4f4d6016f71736105cca16be42c7bf01d5ca15732b17bd",
          "sha1": "712312a11616f05af38e958347dabc04d71e9923",
          "md5": "a973be7407ca836f26b1bac1f848171f"
        }
      ]
    }
  ]
}
