{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-launcher",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-launcher-0.4.1.jar",
          "url": "pancake-launcher-0.4.1.jar",
          "size": 25220,
          "sha512": "93341bb02f81a4d5812613994792930fd5ee61015bbdacd37c0a786446c58d608c32c5c813954954d58392da24f265f78c225234c48146ded998ecd1abef3721",
          "sha256": "6a61adb4c0b23aafb33d1b55fc76971acd6f96f5f81c780d7165324081dcd93c",
          "sha1": "f08ae972b5dc2c0de261c4c99de52e18ace0ee03",
          "md5": "da744ce317ac9e2ec867a4fdb6bb9cef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "pancake-sauce",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.6.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-launcher-0.4.1.jar",
          "url": "pancake-launcher-0.4.1.jar",
          "size": 25220,
          "sha512": "93341bb02f81a4d5812613994792930fd5ee61015bbdacd37c0a786446c58d608c32c5c813954954d58392da24f265f78c225234c48146ded998ecd1abef3721",
          "sha256": "6a61adb4c0b23aafb33d1b55fc76971acd6f96f5f81c780d7165324081dcd93c",
          "sha1": "f08ae972b5dc2c0de261c4c99de52e18ace0ee03",
          "md5": "da744ce317ac9e2ec867a4fdb6bb9cef"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-launcher-0.4.1-all.jar",
          "url": "pancake-launcher-0.4.1-all.jar",
          "size": 6917518,
          "sha512": "680c04a548207edb34a521cf07e4609cd7d0ad09bcba1fc1a90f17b26d80754e5fea3b93567646e1404cc89c5f4e0e5f831b295f78d08cc2509c693c4235c590",
          "sha256": "52c3ecee4f3a745d746df35022a14d6d6c87fe0a9f40c4b6922014d62fb81a5a",
          "sha1": "85d330633feac1aa2bdcfe3a7fa4aa06e98f26c5",
          "md5": "c49371255d7a4d376a417f1712bfa201"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-launcher-0.4.1-sources.jar",
          "url": "pancake-launcher-0.4.1-sources.jar",
          "size": 15602,
          "sha512": "41263439c77b5d934f0e732dcc8fbc86dee387acb694862d6ea1d33c8b2dc58fdffe3bdd55d9c8de20735d57f2b6375296135da87e83ade3d25e19c2976a1a30",
          "sha256": "dbd46352c78fed5a5b9d78052af86e5f44cf4555a45b1710967bc5d21a58cd76",
          "sha1": "08dfa99b6604c95d1fb3ffd73d130ad60c6e82f7",
          "md5": "7b562471d629bfcc3a94afb9ec661b6c"
        }
      ]
    }
  ]
}
