{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.pancake",
    "module": "pancake-launcher",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-launcher-0.4.1.jar",
          "url": "pancake-launcher-0.4.1.jar",
          "size": 25207,
          "sha512": "f811fc9757a6e8d45e7d5633ef5c051547a757b4ff19b9d47e5127dd927d1966a1e8798ee1d7b641b5db75f2613bfd6c38e42a882c8a83de19bcac86d566eea0",
          "sha256": "895f5d986e0bb40df4e61ba96ca18cfccbbd788242b10411fd5e5c7714666da7",
          "sha1": "8d487a161706955ede8b80c7576bf2f11bb68e56",
          "md5": "600290bd823318db9082966fc7fd677e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "sh.pancake",
          "module": "pancake-sauce",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.6.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "sh.pancake",
          "module": "story-network-launch-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            },
            {
              "group": "*",
              "module": "launchwrapper"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-core"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "pancake-launcher-0.4.1.jar",
          "url": "pancake-launcher-0.4.1.jar",
          "size": 25207,
          "sha512": "f811fc9757a6e8d45e7d5633ef5c051547a757b4ff19b9d47e5127dd927d1966a1e8798ee1d7b641b5db75f2613bfd6c38e42a882c8a83de19bcac86d566eea0",
          "sha256": "895f5d986e0bb40df4e61ba96ca18cfccbbd788242b10411fd5e5c7714666da7",
          "sha1": "8d487a161706955ede8b80c7576bf2f11bb68e56",
          "md5": "600290bd823318db9082966fc7fd677e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-launcher-0.4.1-all.jar",
          "url": "pancake-launcher-0.4.1-all.jar",
          "size": 6917505,
          "sha512": "6893e64bd2578682179c10122a9f5639b363467ef667b5355c377b2292f4195a951ab12ecd5c7b3e79fd19f35ce6d2ced563f1775b7be6b8939885598b264b04",
          "sha256": "8c5963ec21bc059c6b1fbcfd82e42a5e62a69925b43eb9d95f123e4a9ec93e40",
          "sha1": "a668f15b52efbf1c920108c51d7b42ca522523c5",
          "md5": "9ca1bce9f21d89cb5b7d5790b5d3ac12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pancake-launcher-0.4.1-sources.jar",
          "url": "pancake-launcher-0.4.1-sources.jar",
          "size": 15591,
          "sha512": "a31f64cf41e5ed0ed528dfb9fd4442c4ecf4f52e18d3b29c8a3b075d8e8609cc27b184befee3b0df58f7946744effe2f40fdc00fa266155382ecc842dfaec508",
          "sha256": "aa8bc9d94187c12e9d30facd0b2feedff67759823f169f925b3f5d07e3145730",
          "sha1": "88be16316227280b8f1ed24450a3591896dac08f",
          "md5": "64d7ed1dd9b9a7d6fb8baacfe5221a81"
        }
      ]
    }
  ]
}
